[package]
name = "ica-native"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.34.2"
egui = "0.34.2"
egui_extras = { version = "0.34.2", features = ["all_loaders"] }

anyhow = "1.0"

foldhash = "0.2.0"
base64 = "0.22"
hex = "0.4"
sha2 = "0.11"
ed25519-dalek = { version = "2.1" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = "0.25"
toml = "1"

# rust_socketio = { git = "https://github.com/nextdata-tech/rust-socketio.git", branch = "tyler/feat-add-features-for-other-tls-types", default-features = false, features = [
rust_socketio = { git = "ssh://git@github.com/nextdata-tech/rust-socketio.git", branch = "tyler/feat-add-features-for-other-tls-types", default-features = false, features = [
    "async",
    "rustls-tls-native-roots",
] }
reqwest = { version = "0.13", default-features = false }

tokio = { version = "1.52.3", features = ["full"] }
futures-util = "0.3.31"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["time", "env-filter"] }
chrono = { version = "0.4.43", features = ["serde"] }
rand = "0.10"
lru = "0.16.3"
rfd = "0.17"
arboard = "3"
urlencoding = "2.1"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_System_DataExchange",
    "Win32_System_Memory",
    "Win32_System_Ole",
    "Win32_UI_Input_KeyboardAndMouse",
] }
