use crate::config::{ChatAppearanceSettings, ConfigStore, ReEditDraftConflictMode};

use super::super::{
    auto_sign::AutoSignState,
    chat_groups::ChatGroupEditor,
    online_mode::OnlineMode,
    open_page::AppOpenPage,
    relation_network::RelationNetworkState,
    settings::ConfigEditor,
    stickers::{StickerPickerTab, StickerStore},
    tools::{
        AccountToolsState, FileToolsState, GroupToolsState, MessageToolsState, RoomToolsState,
    },
};
use super::{BridgeSession, ChatListScrollTarget, ImageViewerState};

pub struct AppState {
    pub custom_chat: ChatAppearanceSettings,
    pub online_mode: OnlineMode,
    pub open_page: AppOpenPage,
    pub mute_all: bool,
    pub mute_any: bool,
    pub notify_level: u8,
    pub chat_group_editor: ChatGroupEditor,
    pub config_editor: ConfigEditor,
    pub chat_list_scroll_target: ChatListScrollTarget,
    pub clear_search_on_room_select: bool,
    pub auto_fetch_history_on_room_select: bool,
    pub scroll_to_bottom_after_send: bool,
    pub reedit_draft_conflict_mode: ReEditDraftConflictMode,
    pub active_bridge_idx: Option<usize>,
    /// Bridge handle, stop signal and UI state are stored in one session object.
    pub bridge_states: Vec<BridgeSession>,
    pub clipboard_paste_failed: bool,
    pub ime_composing: bool,
    pub ime_event_this_frame: bool,
    pub show_face_picker: bool,
    pub show_mention_picker: bool,
    pub mention_search_query: String,
    pub mention_search_focus_requested: bool,
    pub mention_replace_trigger: bool,
    pub image_viewer: Option<std::sync::Arc<std::sync::Mutex<ImageViewerState>>>,
    pub socket_api_event: String,
    pub socket_api_args: String,
    pub socket_api_expect_ack: bool,
    pub socket_api_preset_idx: usize,
    pub group_tools: GroupToolsState,
    pub account_tools: AccountToolsState,
    pub file_tools: FileToolsState,
    pub message_tools: MessageToolsState,
    pub room_tools: RoomToolsState,
    pub auto_sign: AutoSignState,
    pub relation_network: std::sync::Arc<std::sync::Mutex<RelationNetworkState>>,
    pub sticker_store: StickerStore,
    pub sticker_picker_tab: StickerPickerTab,
    pub media_notice: Option<String>,
    pub media_error: Option<String>,
}

impl AppState {
    pub fn new(
        config: &crate::config::IcaCfg,
        store: &ConfigStore,
        bridge_states: Vec<BridgeSession>,
        sticker_store: StickerStore,
    ) -> Self {
        Self {
            custom_chat: config.custom_chat.clone(),
            online_mode: OnlineMode::default(),
            open_page: AppOpenPage::default(),
            mute_any: false,
            mute_all: false,
            notify_level: 3,
            chat_group_editor: ChatGroupEditor::default(),
            config_editor: ConfigEditor::new(store),
            chat_list_scroll_target: ChatListScrollTarget::Top,
            clear_search_on_room_select: config.ui_setting.clear_search_on_room_select,
            auto_fetch_history_on_room_select: config.ui_setting.auto_fetch_history_on_room_select,
            scroll_to_bottom_after_send: config.ui_setting.scroll_to_bottom_after_send,
            reedit_draft_conflict_mode: config.ui_setting.reedit_draft_conflict_mode,
            active_bridge_idx: (!bridge_states.is_empty()).then_some(0),
            bridge_states,
            clipboard_paste_failed: false,
            ime_composing: false,
            ime_event_this_frame: false,
            show_face_picker: false,
            show_mention_picker: false,
            mention_search_query: String::new(),
            mention_search_focus_requested: false,
            mention_replace_trigger: false,
            image_viewer: None,
            socket_api_event: String::new(),
            socket_api_args: "[]".to_string(),
            socket_api_expect_ack: true,
            socket_api_preset_idx: 0,
            group_tools: GroupToolsState::default(),
            account_tools: AccountToolsState::default(),
            file_tools: FileToolsState::default(),
            message_tools: MessageToolsState::default(),
            room_tools: RoomToolsState::default(),
            auto_sign: AutoSignState::default(),
            relation_network: std::sync::Arc::new(std::sync::Mutex::new(
                RelationNetworkState::default()
                    .with_render_setting(config.ui_setting.relation_network.clone()),
            )),
            sticker_store,
            sticker_picker_tab: StickerPickerTab::default(),
            media_notice: None,
            media_error: None,
        }
    }
}
